### ISSUE TITLE
SRI - Add the Verifirer.sol as an zkp artifact to the BPI and env

### ISSUE THREAD

**Issue by ognjenkurtic** [ethereum-oasis-op/baseline#815]
- [x] Do it
- [ ] Extend readme
- [x] Deploy verifier contract in deploy.ts

**Comment by ognjenkurtic** [comment]
@biscuitdey what is the status here? are we going with 3 separate verifier contracts or a single one?

**Comment by biscuitdey** [comment]
> @biscuitdey what is the status here? are we going with 3 separate verifier contracts or a single one?

@ognjenkurtic We are using 3 separate verifier contracts for the 3 worksteps for now, 
because the verification key values are hardcoded inside the contract.
Using one verifier contract (where we pass the verification key as a function
param) is not possible as the contract uses assembly inside solidity contract
and assembly does not accept local variables. Also, if we declare the values as
storage variables, then we would have to change the verifyFunction code it as
there is different syntax to use storage variables.

Andreas suggested that we create a single verifier contract as an improvement later on. This would require us to alter how the verification key variables are called and utilised. Do you suggest we do it now or keep it for later?

**Comment by ognjenkurtic** [comment]
I think contract per workstep is fine for now, we can stick with 3
